### ISSUE TITLE
Deployment bug

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge#10]
There's a bug in the github pages deployment pipeline. The app builds and deploys as expected but the homepage displays a blank body - only the header and footer are visible.

**Comment by radicleart** [comment]
Had a crack at fixing this but no luck. It doesn't happen on normal deployment eg in dev mode. Something to do with the Github Pages reverse proxy settings. 

A related issue is full page loads of nested paths takes the user to a Github 404 page. Again this won't be a problem in production as we'll have control over web server config.

**Comment by igorsyl** [comment]
@sergey-shandar any ideas?

**Comment by radicleart** [comment]
Reopening as because the bug is not yet fixed.

**Comment by radicleart** [comment]
Investigated further and I don't think its due to deployment on github pages. It looks more likely to be due to uncaught errors being thrown while trying to connect to 3rd party apis.

This will be solved by work on other issues and will be closed once resolved.

**Comment by radicleart** [comment]
This may be due to a problem with pre-rendering.

```Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /,  - /admin,  - /history```

noticed this error which may explain why the default route / is missing.

**Comment by sergey-shandar** [comment]
> @sergey-shandar any ideas?

No idea. GitHub pages have to specific build and deploy system. This is the reason that I prefer more generic JAMStack systems like CloudFlare.

**Comment by radicleart** [comment]
This is a bug in the svelte applciation code. I'm still working on it but as a mitigation have changed the  home / landing page to display static content instead of the obviously broken page.

**Comment by radicleart** [comment]
Fixed by other work
