### ISSUE TITLE
Remove multi environment support.

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge#12]
The current version supports toggling between testnet and mainnet in the same deployment as a convenience.

Since this feature isn't needed in the final product I'd like to remove it now as it leads to a lot of unnecessary complexity within the code base.

A better way to handle support for multiple environments is through separate deployments configured via environment variables. This will also provide a clean upgrade/test path for future releases.

In the short term I'd suggest keeping Github Pages for deploying the production (mainnet) build. A staging (testnet) build can be deployed via Docker (on Linode VMs) and used to side step blockers like dependencies on external rpc / api services. Since Github pages cannot be used to host a commercial app it will be helpful to have a testnet deployment thats free of the constraints of Github Pages and that closely mimics the final production setup.

The deployment pipeline will look as follows;

- **Devnet** - build with .env, runs locally (mac)
- **Staging** - build with .env.staging, runs in cloud (initially on Linode/Debian VM)
- **Production** - build with .env.production, runs in cloud (Google / Cloudflare?)

Note 1: server side code is packaged via docker containers so easily relocated.
Note 2: initially the production app will not have a back end. During this period only testing via the staging setup will be possible.

**Comment by radicleart** [comment]
@igorsyl I think this gives us a free run for the development with the possibility of carrying out production deployment activities in parallel. LMK what you think or if you need a more detailed deployment plan?

**Comment by igorsyl** [comment]
Let us select the network in the code only and not in the UI to avoid complications.
We will use mainnet only, but other users could host their bridge in a separate network.
Google Pages or Cloudflare pages for the front-end are ok. 
For the Indexer we will use GCP.

**Comment by radicleart** [comment]
Removed UI network toggle.

[Opened issue 20](https://github.com/Trust-Machines/sbtc-bridge/issues/20) to continue the deployment part of this issue.
