### ISSUE TITLE
sBTC Bridge API

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge#20]
This covers the initial setup of the server side API and the client side application.

The plan is to implement a REST API in two docker containers 

- node js express app
- mongo database

The main role of the REST API will be;

1. Run scheduled tasks to index data from the contract and store as json documents in mongo.
2. Provide end points for reading, filtering, sorting the indexed data.
3. Provide integration with hosted bitcoin and stacks nodes. The main reasons this is needed;
  - provide single interface for extracting all information - e.g. user sbtc / stx / bitcoin balance
  - remove dependency on external, rate limited apis (block cypher, mempool etc)
  - parse data from external nodes / services into single consistent format (e.g. the format of a transaction object read from blockcypher is different to that read from mempool.space - leading to potential errors in the service).

Note: In first instance the bitcoin/stacks integration will be via RPC. Down the line this may be substituted with Hiro Mempool service or Bitcoin Sync sql project.

Note: Requires a new github repository (for the API) and docker configuration.

**Comment by radicleart** [comment]
Just a question - we can compare ElectrumX and Hiro as independent (non third party) solutions for fetching UTXO data?

**Comment by igorsyl** [comment]
@fbwoolf is an expert on Bitcoin indexer solutions, and I value her opinion highly!
