### ISSUE TITLE
Bitcoin fee calculation

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge#3]
Current implementation for forming the tx inputs is incomplete, it;

- pulls up to 200 utxo's per request for the given bitcoin address from mempool
- It sums the values in this output set and presents this as the max peg in amount

The fee calculation is incomplete. Fee rates are read from block cypher api and the user can select high/medium/low rate. The fee calculation is just a fixed multiple of this rate.

The fee calculation [should be based](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1566) on the fee rate (satoshi/bytes) times the size of the signed transaction.

**Comment by igorsyl** [comment]
Tagging @donpdonp for his input on this.

**Comment by radicleart** [comment]
Done. Code uses method 1 described [here](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1566)
