### ISSUE TITLE
Supported Bitcoin Address Types

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge#5]
Decision on Bitcoin addresses to support in first release is needed. Current working assumption is to do the following;

**Supported on Testnet:** 

1. SegWit Testnet (20  byte P2WPKH address) | bc1 | bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4
2. SegWit Testnet (32  byte P2WSH address) | bc1 | bc1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3qccfmv3
3. Testnet script hash (P2SH) | 3 | 3EktnHQD7RiAE6uzMj2ZifT9YgRrkSgzQX

**Supported on Mainnet:** 

1. SegWit Testnet (20  byte P2WPKH address) | tb1 | tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx
2. SegWit Testnet (32  byte P2WSH address) | tb1 | tb1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3q0sl5k7
3. Testnet script hash (P2SH) | 2 | 2MzQwSSnBHWHqSAqtTVQ6v47XtaisrJa1Vc

**Not Supported on either Network**

Legacy addresses (1.. on mainnet and m or n .. on testnet) are not supported.

**Notes**

Note 1: The difference between P2WPKH and P2WSH is the former is satisfied by a signature and the latter by a redeem script.
Note 2: See full list here https://allprivatekeys.com/bitcoin-address-format

**Comment by igorsyl** [comment]
Note: The mainnet addresses have references to "Testnet" as well.
We should prioritize P2WPKH given I believe it's the most popular (can we get stats on this?)
Does the tool complain if unsupported address types are used?

**Comment by radicleart** [comment]
no. currently agnostic of address type. not all tx formats are tested - this might be tricky for legacy txs without control of a legacy address myself.

**Comment by igorsyl** [comment]
It's ok if we have unsupported address types as long as tool shows an error.

**Comment by radicleart** [comment]
For info: [this matrix](https://bitcoinops.org/en/compatibility/) indicates P2WPKH is the default address type supported by the majority of Bitcoin wallets including Electrum, Ledger Live and Trezor. It also shows compatibility with major exchanges.

**Comment by radicleart** [comment]
Helpful reference for [bitcoin-transaction-internals](https://medium.com/coinmonks/bitcoin-transaction-internals-explained-8fd6d4e77eaa).
