### ISSUE TITLE
Magic Bytes missing from peg in / out transactions

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge#60]
Any transaction which contains an OP_RETURN must have the two first bytes of the data to be the configured "magic bytes", else it will be ignored.

```
                if !data.starts_with(self.magic_bytes.as_bytes()) {
                    test_debug!("Data output does not start with magic bytes");
                    return None;
                }
```

Magic bytes on testnet `T2 (0x5432)`  and mainnet `X2 (0x5832)`

So testnet OP_RETURN data for a peg in for example should be;

```
T2 + < + STACKS_ADDRESS = 0x5432 + 3C + STACK_ADRESS_HEX
```

and for mainnet 

```
X2 + < + STACKS_ADDRESS = 0x5832 + 3C + STACK_ADRESS_HEX
```

**Comment by netrome** [comment]
The magic bytes and opcode looks correct to me. However, the stacks address should not be hex-encoded. It should be the compact 21-byte representation of a stacks address corresponding to one version byte and a 20 byte [Hash160](https://www.btcschools.net/bitcoin/bitcoin_tool_hash160.php) public key hash.

**Comment by netrome** [comment]
> The stacks address can be encoded / decoded using the c32check library;
> 
> ```
> import { c32address, c32addressDecode } from 'c32check';
> ```
> 
> and the wire format needs to also support contract principals:
> 
> ```
>             0      2  3                  24                            64       80
>             |------|--|------------------|-----------------------------|--------|
>              magic  op   Stacks address      Contract name (optional)     memo
> ```
> 
> Where contract name is assumed to be an utf-8 encoded string and a valid clarity contract identifier

Sounds good. Just make sure to write the actual bytes of the stacks address, and not the hex-encoded version. The byte array should be 21 bytes long as explained above (version byte + hash160).

**Comment by radicleart** [comment]
Closing as appears to be solved in latest release.
