### ISSUE TITLE
Install Taproot Wallet on Bitcoind 22.0

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge#64]
Marker for this [reddit how to](https://www.reddit.com/r/Bitcoin/comments/r37ky5/howto_create_and_use_a_taproot_wallet_on_testnet/
) .

Extremely helpful on setting up a bitcoin core taproot wallet.

**Comment by donpdonp** [comment]
This brings up the distinction between bitcoin as blockchain server and bitcoin as wallet. I think its worth looking at what advantages, if any, there are by using bitcoind as a wallet.

**Comment by radicleart** [comment]
I ran through the reddit procedure with both use cases. Same end result, aside using bitcoin-cli vs the console.
